use_frameworks!

def reusePods
   pod 'SwiftyMock', :path => '../'
end

target 'SwiftyMock_Example' do
	reusePods
end
    
target 'SwiftyMock_Tests' do
	reusePods

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
end

