platform :ios, '9.3'
use_frameworks!
#inhibit_all_warnings!

def reusePods
  pod 'SwiftyMock/ReactiveCocoa', :path => '../'
end

def reuseTestPods
  reusePods
  pod 'Quick', '~> 1.1.0'
  pod 'Nimble', '~> 7.0.0'
end

target 'SwiftyMock_Example' do
  reusePods
end

target 'SwiftyMock_Tests' do
  reuseTestPods
end

target 'RoboKittenTests' do
  reuseTestPods
end


