platform :ios, '11.0'
use_frameworks!
#inhibit_all_warnings!

def reusePods
  pod 'SwiftyMock/ReactiveCocoa', :path => '../'
end

def reuseTestPods
  reusePods
  pod 'Quick', '~> 5.0'
  # using 7.x-branch for now because of this issue fix https://github.com/Quick/Nimble/issues/478
  # switch to corresponding version once it's released
  pod 'Nimble', '~> 10.0'# :git => 'https://github.com/Quick/Nimble', :branch => '7.x-branch'
end

target 'SwiftyMock_Example' do
  reusePods
end

target 'SwiftyMock_Tests' do
  reuseTestPods
end

target 'RoboKittenTests' do
  reuseTestPods
end


